In [1]:
import re
import requests
from io import StringIO
from datetime import datetime, timedelta
import pandas as pd

In [2]:
# credit:
# https://stackoverflow.com/questions/44225771/scraping-historical-data-from-yahoo-finance-with-python?rq=1

In [3]:
class YFH: #YFH = YahooFinanceHistory
    timeout = 2
    crumb_link = 'https://finance.yahoo.com/quote/{0}/history?p={0}'
    crumble_regex = r'CrumbStore":{"crumb":"(.*?)"}'
    quote_link = 'https://query1.finance.yahoo.com/v7/finance/download/{quote}?period1={dfrom}&period2={dto}&interval=1d&events=history&crumb={crumb}'
    
    def __init__(self, symbol, days_back=7):
        self.symbol = symbol
        self.session = requests.Session()
        self.dt = timedelta(days=days_back)
        
    def get_crumb(self):
        response = self.session.get(self.crumb_link.format(self.symbol), timeout=self.timeout)
        response.raise_for_status()
        match = re.search(self.crumble_regex, response.text)
        if not match:
            raise ValueError('Could not get crumb from Yahoo Finance')
        else: 
            self.crumb = match.group(1)
        
    def get_quote(self):
        if not hasattr(self, 'crumb') or len(self.session.cookies) == 0:
            self.get_crumb()
        now = datetime.utcnow()
        dateto = int(now.timestamp())
        datefrom = int((now - self.dt).timestamp())
        url = self.quote_link.format(quote=self.symbol, dfrom=datefrom, dto=dateto, crumb=self.crumb)
        response = self.session.get(url)
        response.raise_for_status()
        return pd.read_csv(StringIO(response.text), parse_dates=['Date'])

In [4]:
df = YFH('AAPL', days_back=365*5).get_quote()
df['Symbol'] = 'AAPL'
cols = df.columns.tolist()
cols = cols[-1:] + cols[:-1]
df = df[cols]
df

,Symbol,Date,Open,High,Low,Close,Adj Close,Volume
0,AAPL,2013-12-17,79.401428,79.919998,79.054283,79.284286,67.477669,57475600
1,AAPL,2013-12-18,78.528572,78.778572,76.971428,78.681427,66.964600,141465800
2,AAPL,2013-12-19,78.500000,78.571426,77.675713,77.779999,66.197380,80077200
3,AAPL,2013-12-20,77.918571,78.801430,77.831429,78.431427,66.751823,109103400
4,AAPL,2013-12-23,81.142860,81.531425,80.394287,81.441429,69.313591,125326600
5,AAPL,2013-12-24,81.412857,81.697144,80.861427,81.095711,69.019356,41888700
6,AAPL,2013-12-26,81.157143,81.357140,80.482857,80.557144,68.560997,51002000
7,AAPL,2013-12-27,80.545715,80.629997,79.928574,80.012856,68.097748,56471100
8,AAPL,2013-12-30,79.637146,80.012856,78.902855,79.217140,67.420517,63407400
9,AAPL,2013-12-31,79.167145,80.182854,79.142860,80.145714,68.210831,55771100
10,AAPL,2014-01-02,79.382858,79.575714,78.860001,79.018570,67.251503,58671200
11,AAPL,2014-01-03,78.980003,79.099998,77.204285,77.282860,65.774300,98116900
12,AAPL,2014-01-06,76.778572,78.114288,76.228569,77.704285,66.132957,103152700
13,AAPL,2014-01-07,77.760002,77.994286,76.845711,77.148575,65.660004,79302300
14,AAPL,2014-01-08,76.972855,77.937141,76.955711,77.637146,66.075813,64632400
15,AAPL,2014-01-09,78.114288,78.122856,76.478569,76.645714,65.232025,69787200
16,AAPL,2014-01-10,77.118568,77.257141,75.872856,76.134285,64.796753,76244000
17,AAPL,2014-01-13,75.701431,77.500000,75.697144,76.532860,65.135979,94623200
18,AAPL,2014-01-14,76.888573,78.104286,76.808571,78.055717,66.432060,83140400
19,AAPL,2014-01-15,79.074287,80.028572,78.808571,79.622856,67.765808,97909700
20,AAPL,2014-01-16,79.271431,79.550003,78.811432,79.178574,67.387703,57319500
21,AAPL,2014-01-17,78.782860,78.867142,77.128571,77.238571,65.736603,106684900
22,AAPL,2014-01-21,77.284286,78.581429,77.202858,78.438568,66.757919,82131700
23,AAPL,2014-01-22,78.701431,79.612854,78.258568,78.787140,67.054565,94996300
24,AAPL,2014-01-23,78.562859,79.500000,77.830002,79.454285,67.622375,100809800
25,AAPL,2014-01-24,79.142860,79.374283,77.821426,78.010002,66.393143,107338700
26,AAPL,2014-01-27,78.581429,79.257141,77.964287,78.642860,66.931786,138719700
27,AAPL,2014-01-28,72.680000,73.571426,71.724289,72.357140,61.582092,266380800
28,AAPL,2014-01-29,71.992859,72.481430,71.231430,71.535713,60.882980,125702500
29,AAPL,2014-01-30,71.791428,72.357140,70.957146,71.397141,60.765038,169625400
...,...,...,...,...,...,...,...,...
1228,AAPL,2018-11-01,219.050003,222.360001,216.809998,222.220001,221.447327,58323200
1229,AAPL,2018-11-02,209.550003,213.649994,205.429993,207.479996,206.758575,91328700
1230,AAPL,2018-11-05,204.300003,204.389999,198.169998,201.589996,200.889053,66163700
1231,AAPL,2018-11-06,201.919998,204.720001,201.690002,203.770004,203.061493,31882900
1232,AAPL,2018-11-07,205.970001,210.059998,204.130005,209.949997,209.219986,33424400
1233,AAPL,2018-11-08,209.979996,210.119995,206.750000,208.490005,208.490005,25362600
1234,AAPL,2018-11-09,205.550003,206.009995,202.250000,204.470001,204.470001,34365800
1235,AAPL,2018-11-12,199.000000,199.850006,193.789993,194.169998,194.169998,51135500
1236,AAPL,2018-11-13,191.630005,197.179993,191.449997,192.229996,192.229996,46882900
1237,AAPL,2018-11-14,193.899994,194.479996,185.929993,186.800003,186.800003,60801000
1238,AAPL,2018-11-15,188.389999,191.970001,186.899994,191.410004,191.410004,46478800
1239,AAPL,2018-11-16,190.500000,194.970001,189.460007,193.529999,193.529999,36928300
1240,AAPL,2018-11-19,190.000000,190.699997,184.990005,185.860001,185.860001,41925300
1241,AAPL,2018-11-20,178.369995,181.470001,175.509995,176.979996,176.979996,67825200
1242,AAPL,2018-11-21,179.729996,180.270004,176.550003,176.779999,176.779999,31124200
1243,AAPL,2018-11-23,174.940002,176.600006,172.100006,172.289993,172.289993,23624000
1244,AAPL,2018-11-26,174.240005,174.949997,170.259995,174.619995,174.619995,44738600
1245,AAPL,2018-11-27,171.509995,174.770004,170.880005,174.240005,174.240005,41387400
1246,AAPL,2018-11-28,176.729996,181.289993,174.929993,180.940002,180.940002,46062500
1247,AAPL,2018-11-29,182.660004,182.800003,177.699997,179.550003,179.550003,41770000
1248,AAPL,2018-11-30,180.289993,180.330002,177.029999,178.580002,178.580002,39531500
1249,AAPL,2018-12-03,184.460007,184.940002,181.210007,184.820007,184.820007,40802500
1250,AAPL,2018-12-04,180.949997,182.389999,176.270004,176.690002,176.690002,41344300
1251,AAPL,2018-12-06,171.759995,174.779999,170.419998,174.720001,174.720001,43098400
1252,AAPL,2018-12-07,173.490005,174.490005,168.300003,168.490005,168.490005,42281600
1253,AAPL,2018-12-10,165.000000,170.089996,163.330002,169.600006,169.600006,62026000
1254,AAPL,2018-12-11,171.660004,171.789993,167.000000,168.630005,168.630005,47281700
1255,AAPL,2018-12-12,170.399994,171.919998,169.020004,169.100006,169.100006,35627700
1256,AAPL,2018-12-13,170.490005,172.570007,169.550003,170.949997,170.949997,31898600
1257,AAPL,2018-12-14,169.000000,169.080002,165.279999,165.479996,165.479996,40634300